name: Deploy Serverless Application

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Align this with the Lambda's runtime version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Install Serverless and plugins
        run: |
          npm install -g serverless@3.6  # Ensure the correct version of Serverless is used
          npm install -g serverless-python-requirements  # Install required Serverless plugin

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1  # Use the same region as in your serverless.yml

      - name: Deploy with Serverless Framework
        run: serverless deploy
